### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by Jacky-LinPeng** [lexiaoyao20/FMActionSheet#1]
我在这里面看到你提了一个问题，所以想找你请教你下
https://github.com/61bcdefg/Hikari-LLVM15/issues/121

前言：
<img width="280" alt="image" src="https://github.com/user-attachments/assets/1f2e1b59-3aa5-4eac-9c3d-a078986c26b2">

1、我在这里下载了编译好工具链：Hikari_LLVM18.1.8_Intel-Mac
2、我将其放到Toolchains/目录下
3、新建一个OC工程、跑模拟器编译报错
<img width="1462" alt="image" src="https://github.com/user-attachments/assets/cae7e15b-de6a-43fe-8369-3212820bcba9">
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/af2d6dcb-ea69-4d29-9234-90d10992f7c1">

以上的步骤是不是做错了啥？不能直接这么运行还是要制定再配置一些参数？希望得到你的知道，万分感谢

**Comment by lexiaoyao20** [comment]
直接用Xcode默认的ToolChain编译是正常的吗？如果正常的话，就只有可能是 Hikari_LLVM18.1.8_Intel-Mac 与你的Xcode不兼容。这里有[Xcode对应的ToolChain Version](https://en.wikipedia.org/wiki/Xcode#Toolchain_versions)，你可以参考一下

**Comment by Jacky-LinPeng** [comment]
1、Xcode默认的ToolChain编译是正常的
2、我想再咨询一下：你是自己下载llvm的源码 然后结合Hikari、再编译出toolchains使用吗？如果是的话，那llvm的源码是从apple（ https://github.com/swiftlang/llvm-project/）下的？还是llvm官方（https://github.com/llvm/llvm-project）下的？
3、你编译出来的toolchains、oc和swift混编的工程都能成功编译吗？
4、编译出来的toolchains、有用来App打包上架么？能过审不😄

希望得到大佬的指导

**Comment by lexiaoyao20** [comment]
我自己有编译过 llvm 工程，你可以参考这篇：[XCode15.4下编译Hikari笔记](https://blog.csdn.net/jian274622701/article/details/139130224)，也可以直接拿Hikari作者已经编译好的直接拿来用：
[apple-arm64e-upstream-next Toolchain](https://github.com/61bcdefg/Hikari-LLVM15/actions/runs/9833500990)
![toolchain](https://github.com/user-attachments/assets/76d20b8f-95e1-4b49-9434-1ef7d1490182)

我这边OC可以正常混淆编译，Swift不行，可能需要用其他的ToolChain

**Comment by Jacky-LinPeng** [comment]
我的[Hikari_LLVM18.1.8_Intel-Mac](https://github.com/61bcdefg/Hikari-LLVM15/actions/runs/10449039187)就是作者编译好的，结果纯OC的工程都编译运行报错
[apple-arm64e-upstream-next Toolchain](https://github.com/61bcdefg/Hikari-LLVM15/actions/runs/9833500990)这个过期了、无法下载、
作者在前几天10月1号的宣布不再支持维护Hikari、真的遗憾，

**Comment by lexiaoyao20** [comment]
你可以根据 HiKari 的 [Github action workflow](https://github.com/61bcdefg/Hikari-LLVM15/actions/runs/9833500990/workflow) 里面的步骤，自己来编译一个ToolChain，看看是否能正常编译。
![1111](https://github.com/user-attachments/assets/d3f499cd-482c-408d-bcef-5117dbf49ee6)

**Comment by Jacky-LinPeng** [comment]
我编译出来几个、但是都不行、还是一些奇怪的报错、我看你上次根作者交流、你是具体复制了哪些内容？
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/76791c8e-faf9-4e7e-af38-94d5442dc02f">


我的报错：是不是还要在工程里面配置一些参数？
<img width="730" alt="image" src="https://github.com/user-attachments/assets/1e73cf4d-bd10-4775-90f4-93add0dcb635">

**Comment by lexiaoyao20** [comment]
我复制的是Swift的相关的内容，我上面的回复已经说了复制的具体内容了。
看你的错误，我怀疑你的ToolChain是 M系列芯片的，而不是Intel芯片，所以报错 Bad CPU type...
我这边复制后的ToolChain lib目录，你可以对比一下：
<img width="1287" alt="截屏2024-10-18 下午5 35 19" src="https://github.com/user-attachments/assets/cfffccbc-368e-49ec-bb2c-9511a6f54c99">

**Comment by Jacky-LinPeng** [comment]
很奇怪、今天都可以正常编译demo、那天应该电脑问题、重启治百病！
<img width="814" alt="image" src="https://github.com/user-attachments/assets/2427ef4e-ae1d-455a-8de9-99940aeb2dcd">
